spring.datasource.url=jdbc:mysql://localhost:3306/foodserve?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Tusha@1998

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

rapidapi.key=782e3b0dbfmsh5c3b9dcda6037dcp1f19fcjsn13cea1f07330
rapidapi.host=irctc1.p.rapidapi.com
rapidapi.url=https://irctc1.p.rapidapi.com/api/v3/getLiveStation
