

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=QDFUbdomXFbZQeTkuJyPSmKGORGSbFMX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

rapidapi.key=782e3b0dbfmsh5c3b9dcda6037dcp1f19fcjsn13cea1f07330
rapidapi.host=irctc1.p.rapidapi.com
rapidapi.url=https://irctc1.p.rapidapi.com/api/v3/getLiveStation

# application.properties
jwt.secret=mySuperSecretKeyForJwtAuthentication12345678901234567
razorpay.key=rzp_test_Sq4Unk8n88bXHr
razorpay.secret=r0InnNK1ZQmMM0v9W3tbFS2q